server:
  port: 8081

spring:
    datasource:
        name: c3p0
        jdbcUrl: jdbc:oracle:thin:@//127.0.0.1/ORCL
        user: zpl
        password: 123456
        # 使用c3p0数据源
        type: com.mchange.v2.c3p0.DriverManagerDataSource
        driverClass: oracle.jdbc.driver.OracleDriver
        minPoolSize: 2
        maxPoolSize: 10
        maxIdleTime: 1800000
        acquireIncrement: 3
        maxStatements: 1000
        initialPoolSize: 3
        idleConnectionTestPeriod: 60
        acquireRetryAttempts: 30
        acquireRetryDelay: 1000
        breakAfterAcquireFailure: false
        testConnectionOnCheckout: false
    mvc:
        view:
              prefix: /WEB-INF/views/
              suffix: .jsp
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package:  com.zpl.springboot_mybatis.model # 注意：对应实体类的路径